server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitydb?serverTimezone=Asia/Seoul
    username: root
    password: novanov2
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 11681411196-481oj0bto50aerlt7ar5j42log08eplh.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile


